services:
  postgres:
    image: postgres:18.4-bookworm
    container_name: schematic-pg-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgrest
      POSTGRES_PASSWORD: postgrest
      POSTGRES_DB: postgrest
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgrest -d postgrest"]
      interval: 5s
      timeout: 5s
      retries: 5
