import { PACKAGE_NAME } from '../constants.js';
import type { Schema } from '../schema-dsl/ast.js';
import { buildModelMetaSnapshot } from './model-meta.js';
import { getClientExportName, TypeGenerator } from './type-generator.js';

export class DbClientGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const imports = this.schema.models
      .flatMap((model) => [
        model.name,
        `${model.name}CreateInput`,
        `${model.name}UpdateInput`,
        `${model.name}WhereInput`,
        `${model.name}OrderByInput`,
      ])
      .join(',\n  ');

    const clientEntries = this.schema.models.map((model) => this.generateClientEntry(model.name));

    return [
      '// Auto-generated by DbClientGenerator. Do not edit manually.',
      "import type { Pool } from 'pg';",
      `import { createModelClient } from '${PACKAGE_NAME}/db/model-client';`,
      `import { hydrateModelMeta } from '${PACKAGE_NAME}/db/model-meta';`,
      `import type {\n  ${imports},\n} from './db-types.js';`,
      `import {\n  ${this.schema.models.map((model) => `${getClientExportName(model.name)}ModelMeta`).join(',\n  ')},\n} from './db-model-meta.js';`,
      '',
      'export function createDbClient(pool: Pool) {',
      ...this.schema.models.map((model) => {
        const clientKey = getClientExportName(model.name);
        return `  const ${clientKey}Meta = hydrateModelMeta(${clientKey}ModelMeta);`;
      }),
      '',
      '  return {',
      clientEntries.map((entry) => `    ${entry},`).join('\n'),
      '  };',
      '}',
      '',
      'export type DbClient = ReturnType<typeof createDbClient>;',
      '',
    ].join('\n');
  }

  generateModelMetaModule(): string {
    const blocks = this.schema.models.map((model) => {
      const meta = buildModelMetaSnapshot(model, this.schema);
      const clientKey = getClientExportName(model.name);
      return `export const ${clientKey}ModelMeta = ${JSON.stringify(meta, null, 2)} as const;`;
    });

    return [
      '// Auto-generated model metadata. Do not edit manually.',
      `import type { ModelMetaSnapshot } from '${PACKAGE_NAME}/db/model-meta';`,
      '',
      ...blocks,
      '',
    ].join('\n');
  }

  private generateClientEntry(modelName: string): string {
    const clientKey = getClientExportName(modelName);
    return `${clientKey}: createModelClient<${modelName}, ${modelName}CreateInput, ${modelName}UpdateInput, ${modelName}WhereInput, ${modelName}OrderByInput>(${clientKey}Meta, pool)`;
  }
}

export function generateDbClientFiles(schema: Schema): { dbTypes: string; dbClient: string; modelMeta: string } {
  const typeGenerator = new TypeGenerator(schema);
  const dbClientGenerator = new DbClientGenerator(schema);

  return {
    dbTypes: typeGenerator.generate(),
    dbClient: dbClientGenerator.generate(),
    modelMeta: dbClientGenerator.generateModelMetaModule(),
  };
}
