import type { Field, Model, Schema, TypeExpr } from '../schema-dsl/ast.js';
import {
  fieldHasAttribute,
  getModelNames,
  getStoredFields,
} from '../sql-generator/utils/ast-helpers.js';
import { toClientKey } from './utils/naming.js';

export class TypeGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const enumBlocks = this.schema.enums.map((enumDef) => this.generateEnumType(enumDef.name, enumDef.values));
    const modelBlocks = this.schema.models.flatMap((model) => this.generateModelTypes(model));

    return [
      '// Auto-generated by TypeGenerator. Do not edit manually.',
      '',
      ...enumBlocks,
      ...modelBlocks,
    ].join('\n');
  }

  private generateEnumType(name: string, values: string[]): string {
    const union = values.map((value) => `'${value}'`).join(' | ');
    return `export type ${name} = ${union};\n`;
  }

  private generateModelTypes(model: Model): string[] {
    const modelNames = getModelNames(this.schema);
    const storedFields = getStoredFields(model, modelNames);

    return [
      this.generateEntityInterface(model.name, storedFields),
      this.generateCreateInput(model.name, storedFields),
      this.generateUpdateInput(model.name, storedFields),
      this.generateWhereInput(model.name, storedFields),
      this.generateOrderByInput(model.name, storedFields),
      '',
    ];
  }

  private generateEntityInterface(modelName: string, fields: Field[]): string {
    const lines = fields.map((field) => `  ${field.name}: ${this.toTsType(field, 'entity')};`);
    return `export interface ${modelName} {\n${lines.join('\n')}\n}\n`;
  }

  private generateCreateInput(modelName: string, fields: Field[]): string {
    const lines = fields
      .filter((field) => !fieldHasAttribute(field, 'id'))
      .map((field) => {
        const optionalMarker = field.type.optional || fieldHasAttribute(field, 'default') ? '?' : '';
        return `  ${field.name}${optionalMarker}: ${this.toTsType(field, 'input')};`;
      });

    return `export interface ${modelName}CreateInput {\n${lines.join('\n')}\n}\n`;
  }

  private generateUpdateInput(modelName: string, fields: Field[]): string {
    const lines = fields
      .filter((field) => !fieldHasAttribute(field, 'id'))
      .map((field) => `  ${field.name}?: ${this.toTsType(field, 'input')};`);

    return `export interface ${modelName}UpdateInput {\n${lines.join('\n')}\n}\n`;
  }

  private generateWhereInput(modelName: string, fields: Field[]): string {
    const filterableFields = fields.filter((field) => this.isFilterable(field));
    const lines = filterableFields.map((field) => `  ${field.name}?: ${this.toWhereFieldType(field)};`);
    lines.push('  AND?: ' + modelName + 'WhereInput[];');
    lines.push('  OR?: ' + modelName + 'WhereInput[];');
    lines.push('  NOT?: ' + modelName + 'WhereInput;');

    return `export interface ${modelName}WhereInput {\n${lines.join('\n')}\n}\n`;
  }

  private generateOrderByInput(modelName: string, fields: Field[]): string {
    const lines = fields.map((field) => `  ${field.name}?: 'asc' | 'desc';`);
    return `export interface ${modelName}OrderByInput {\n${lines.join('\n')}\n}\n`;
  }

  private toTsType(field: Field, mode: 'entity' | 'input'): string {
    const base = this.mapTypeExpr(field.type);

    if (field.type.optional) {
      return `${base} | null`;
    }

    if (mode === 'input' && fieldHasAttribute(field, 'default')) {
      return base;
    }

    return base;
  }

  private mapTypeExpr(type: TypeExpr): string {
    const enumType = this.schema.enums.find((enumDef) => enumDef.name === type.name);
    if (enumType) {
      return type.name;
    }

    if (type.array && type.name === 'TEXT') {
      return 'string[]';
    }

    switch (type.name) {
      case 'UUID':
      case 'VARCHAR':
      case 'TEXT':
        return 'string';
      case 'INTEGER':
      case 'SERIAL':
      case 'SMALLINT':
        return 'number';
      case 'BOOLEAN':
        return 'boolean';
      case 'TIMESTAMP':
        return 'Date';
      case 'DECIMAL':
        return 'string';
      case 'JSONB':
        return 'Record<string, unknown>';
      case 'POINT':
        return 'unknown';
      default:
        return 'unknown';
    }
  }

  private isFilterable(field: Field): boolean {
    const typeName = field.type.name;
    return !this.schema.models.some((model) => model.name === typeName);
  }

  private toWhereFieldType(field: Field): string {
    const base = this.mapTypeExpr(field.type);
    const scalar = field.type.optional ? `${base} | null` : base;
    const filters: string[] = [`{ equals: ${scalar} }`];
    const isStringType = ['UUID', 'VARCHAR', 'TEXT'].includes(field.type.name);
    const isEnumType = this.schema.enums.some((enumDef) => enumDef.name === field.type.name);

    if (isStringType) {
      filters.push(`{ contains: string }`, `{ startsWith: string }`, `{ endsWith: string }`);
    }

    if (isEnumType) {
      filters.push(`{ in: ${base}[] }`);
    }

    if (['INTEGER', 'SERIAL', 'SMALLINT', 'DECIMAL'].includes(field.type.name)) {
      filters.push(
        `{ gt: ${base} }`,
        `{ gte: ${base} }`,
        `{ lt: ${base} }`,
        `{ lte: ${base} }`,
      );
    }

    if (field.type.name === 'BOOLEAN') {
      return scalar;
    }

    return [scalar, ...filters].join(' | ');
  }
}

export function generateDbTypes(schema: Schema): string {
  return new TypeGenerator(schema).generate();
}

export function getClientExportName(modelName: string): string {
  return toClientKey(modelName);
}
