// Run: npm test

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';
import { parse } from '../../schema-dsl/index.js';
import { generateApiFiles } from '../index.js';
import { OpenApiGenerator } from '../openapi-generator.js';
import { generateAppFile } from '../app-generator.js';

const schemaSource = readFileSync(path.resolve('app.schema'), 'utf8');
const schema = parse(schemaSource);
const missingCustomRoutesDir = path.resolve('src/api-generator/__tests__/fixtures/missing-routes');
const fixtureCustomRoutesDir = path.resolve('src/api-generator/__tests__/fixtures/custom-routes');
const fixtureAuthRoutesDir = path.resolve('src/api-generator/__tests__/fixtures/custom-routes-auth');

describe('OpenApiGenerator', () => {
  it('emits OpenAPI 3.1 CRUD paths, filters, omit, and bearer auth', () => {
    const document = new OpenApiGenerator(schema).generate();

    assert.equal(document.openapi, '3.1.0');

    const paths = document.paths as Record<string, Record<string, unknown>>;
    assert.ok(paths['/users']);
    assert.ok(paths['/users']?.get);
    assert.ok(paths['/users']?.post);
    assert.ok(paths['/users/{id}']?.get);
    assert.ok(paths['/users/{id}']?.put);
    assert.ok(paths['/users/{id}']?.delete);
    assert.ok(paths['/product-orders/{orderId}/{productId}']?.get);

    const listParams = (paths['/users'].get as { parameters: Array<{ name: string }> }).parameters;
    const paramNames = listParams.map((param) => param.name);
    assert.ok(paramNames.includes('email_contains'));
    assert.ok(paramNames.includes('limit'));
    assert.ok(paramNames.includes('include'));
    assert.ok(paramNames.includes('offset'));
    assert.ok(paramNames.includes('sort'));

    const schemas = (document.components as { schemas: Record<string, { properties?: Record<string, unknown> }> })
      .schemas;
    assert.ok(schemas.UserResponse?.properties);
    assert.equal(schemas.UserResponse.properties?.passwordHash, undefined);
    assert.ok(schemas.UserCreate?.properties?.passwordHash);
    assert.ok(schemas.Error?.properties?.error);

    const createResponses = (
      paths['/users'].post as {
        responses: Record<
          string,
          {
            description: string;
            content: { 'application/json': { example: { error: string } } };
          }
        >;
      }
    ).responses;
    assert.deepEqual(createResponses['400'].content['application/json'].example, {
      error: 'Validation failed',
    });
    assert.deepEqual(createResponses['409'].content['application/json'].example, {
      error: 'Unique constraint violation on email',
    });
    assert.deepEqual(createResponses['403'].content['application/json'].example, {
      error: 'Role "USER" is not allowed to list this resource',
    });

    const securitySchemes = (
      document.components as { securitySchemes: Record<string, { type: string; scheme: string }> }
    ).securitySchemes;
    assert.equal(securitySchemes.bearerAuth?.type, 'http');
    assert.equal(securitySchemes.bearerAuth?.scheme, 'bearer');

    assert.equal(paths['/auth/register'], undefined);
  });

  it('includes known auth paths when includeAuthPaths is true', () => {
    const document = new OpenApiGenerator(schema, { includeAuthPaths: true }).generate();
    const paths = document.paths as Record<string, unknown>;

    assert.ok(paths['/auth/register']);
    assert.ok(paths['/auth/login']);
    assert.ok(paths['/auth/me']);
  });

  it('generateTsModule and generateJson stay in sync', () => {
    const generator = new OpenApiGenerator(schema);
    const json = JSON.parse(generator.generateJson());
    const tsModule = generator.generateTsModule();

    assert.match(tsModule, /Auto-generated by OpenApiGenerator/);
    assert.match(tsModule, /export const openApiDocument =/);
    assert.equal(json.openapi, '3.1.0');
    assert.deepEqual(json, generator.generate());
  });
});

describe('OpenAPI generateApiFiles integration', () => {
  it('emits openapi artifacts and detects auth custom route', () => {
    const withoutAuth = generateApiFiles(schema, { customRoutesDir: fixtureCustomRoutesDir });
    assert.doesNotMatch(withoutAuth.openapiJson, /"\/auth\/register"/);

    const withAuth = generateApiFiles(schema, { customRoutesDir: fixtureAuthRoutesDir });
    assert.match(withAuth.openapiJson, /"\/auth\/register"/);
    assert.match(withAuth.openapiTs, /export const openApiDocument =/);
    assert.match(withAuth.app, /mountApiDocs\(app, openApiDocument\)/);
  });
});

describe('AppGenerator OpenAPI mount', () => {
  it('mounts docs routes before middleware', () => {
    const output = generateAppFile(schema, { customRoutesDir: missingCustomRoutesDir });

    assert.match(output, /import \{ openApiDocument \} from '\.\/openapi\.js'/);
    assert.match(output, /import \{ mountApiDocs \} from 'schematic-pg\/api\/openapi'/);
    assert.match(output, /mountApiDocs\(app, openApiDocument\)/);
    assert.match(output, /API docs at http:\/\/localhost:\$\{port\}\/docs/);

    const mountIndex = output.indexOf('mountApiDocs(app, openApiDocument)');
    const loggerIndex = output.indexOf('app.use(logger())');
    assert.ok(mountIndex >= 0);
    assert.ok(loggerIndex > mountIndex);
  });
});
