import path from 'node:path';
import { PACKAGE_NAME } from '../constants.js';
import type { Schema } from '../schema-dsl/ast.js';
import {
  discoverCustomRoutes,
  partitionCustomRoutes,
  type CustomRouteMountEntry,
} from './custom-route-scanner.js';
import { getRouteMountEntries } from './route-generator.js';

export interface AppGeneratorOptions {
  customRoutesDir?: string;
  /** When provided, skip re-discovering and use these standalone mounts only. */
  standaloneCustomRoutes?: CustomRouteMountEntry[];
  overlays?: ReadonlyMap<string, CustomRouteMountEntry>;
}

const DEFAULT_CUSTOM_ROUTES_DIR = path.resolve('src/routes');

export class AppGenerator {
  constructor(
    private readonly schema: Schema,
    private readonly options: AppGeneratorOptions = {},
  ) {}

  generate(): string {
    const overlays = this.options.overlays ?? new Map<string, CustomRouteMountEntry>();
    const mounts = getRouteMountEntries(this.schema, overlays);
    const generatedImports = mounts
      .map((entry) => `import ${entry.importName} from './routes/${entry.fileName.replace(/\.ts$/, '.js')}';`)
      .join('\n');
    const generatedRoutes = mounts
      .map((entry) => `  app.route('/${entry.basePath}', ${entry.importName});`)
      .join('\n');

    const standaloneMounts = this.resolveStandaloneCustomRoutes();
    const customImports = standaloneMounts
      .map((entry) => `import ${entry.importName} from '${entry.importPath}';`)
      .join('\n');
    const customRoutes = standaloneMounts
      .map((entry) => `  app.route('/${entry.basePath}', ${entry.importName});`)
      .join('\n');

    const routeImports = [generatedImports, customImports].filter(Boolean).join('\n');
    const routeMounts = [generatedRoutes, customRoutes].filter(Boolean).join('\n');

    return [
      '// Auto-generated by AppGenerator. Do not edit manually.',
      "import { pathToFileURL } from 'node:url';",
      "import { Pool } from 'pg';",
      "import { Hono } from 'hono';",
      "import { logger } from 'hono/logger';",
      "import { prettyJSON } from 'hono/pretty-json';",
      "import { serve } from '@hono/node-server';",
      routeImports,
      "import { createDbClient } from './db.js';",
      "import { POLICIES } from './policies.js';",
      "import { HOOKS } from './hooks.js';",
      "import { openApiDocument } from './openapi.js';",
      `import { configurePolicies } from '${PACKAGE_NAME}/api/auth/policy';`,
      `import { configureHooks } from '${PACKAGE_NAME}/api/hooks';`,
      `import { createAuthMiddleware } from '${PACKAGE_NAME}/api/auth/middleware';`,
      `import { createJwtResolver } from '${PACKAGE_NAME}/api/auth/jwt-resolver';`,
      `import type { AuthResolver } from '${PACKAGE_NAME}/api/auth/types';`,
      `import { createCorsMiddleware } from '${PACKAGE_NAME}/api/middleware/cors';`,
      `import { createDbMiddleware } from '${PACKAGE_NAME}/api/middleware/db';`,
      `import { handleError } from '${PACKAGE_NAME}/api/middleware/errors';`,
      `import { mountApiDocs } from '${PACKAGE_NAME}/api/openapi';`,
      `import type { AppEnv } from '${PACKAGE_NAME}/api/types';`,
      '',
      'configurePolicies(POLICIES);',
      'configureHooks(HOOKS);',
      '',
      'export interface CreateAppOptions {',
      '  pool?: Pool;',
      '  authResolver?: AuthResolver;',
      '}',
      '',
      'export function createApp(options: CreateAppOptions = {}): Hono<AppEnv> {',
      '  const app = new Hono<AppEnv>();',
      '  app.use(createCorsMiddleware());',
      '  mountApiDocs(app, openApiDocument);',
      '  app.use(logger());',
      '  app.use(prettyJSON());',
      '  app.use(createDbMiddleware({ pool: options.pool, createDbClient }));',
      '  app.use(createAuthMiddleware(options.authResolver ?? createJwtResolver()));',
      '  app.onError(handleError);',
      '',
      routeMounts,
      '',
      '  return app;',
      '}',
      '',
      'const isMain = import.meta.url === pathToFileURL(process.argv[1] ?? \'\').href;',
      '',
      'if (isMain) {',
      '  const port = Number(process.env.PORT ?? 3000);',
      '  serve({ fetch: createApp().fetch, port }, () => {',
      '    console.log(`Server running at http://localhost:${port}`);',
      '    console.log(`API docs at http://localhost:${port}/docs`);',
      '  });',
      '}',
      '',
    ].join('\n');
  }

  private resolveStandaloneCustomRoutes(): CustomRouteMountEntry[] {
    if (this.options.standaloneCustomRoutes) {
      return this.options.standaloneCustomRoutes;
    }

    const customRoutesDir = this.options.customRoutesDir ?? DEFAULT_CUSTOM_ROUTES_DIR;
    const { standalone } = partitionCustomRoutes(discoverCustomRoutes(customRoutesDir), this.schema);
    return standalone;
  }
}

export function generateAppFile(schema: Schema, options?: AppGeneratorOptions): string {
  return new AppGenerator(schema, options).generate();
}
