import type { Schema } from '../schema-dsl/ast.js';
import { getRouteMountEntries } from './route-generator.js';

export class AppGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const mounts = getRouteMountEntries(this.schema);
    const imports = mounts.map((entry) => `import ${entry.importName} from './routes/${entry.fileName.replace(/\.ts$/, '.js')}';`).join('\n');
    const routes = mounts.map((entry) => `app.route('/${entry.basePath}', ${entry.importName});`).join('\n');

    return [
      '// Auto-generated by AppGenerator. Do not edit manually.',
      "import { Hono } from 'hono';",
      "import { logger } from 'hono/logger';",
      "import { prettyJSON } from 'hono/pretty-json';",
      "import { serve } from '@hono/node-server';",
      imports,
      "import { createDbMiddleware } from '../src/api/middleware/db.js';",
      "import { handleError } from '../src/api/middleware/errors.js';",
      '',
      'const app = new Hono();',
      'app.use(logger());',
      'app.use(prettyJSON());',
      'app.use(createDbMiddleware());',
      'app.onError(handleError);',
      '',
      routes,
      '',
      'const port = Number(process.env.PORT ?? 3000);',
      'serve({ fetch: app.fetch, port }, () => {',
      '  console.log(`Server running at http://localhost:${port}`);',
      '});',
      '',
    ].join('\n');
  }
}

export function generateAppFile(schema: Schema): string {
  return new AppGenerator(schema).generate();
}
