import { PACKAGE_NAME } from '../constants.js';
import type { Schema } from '../schema-dsl/ast.js';
import {
  hasPolicies,
  normalizePolicies,
  type NormalizedPolicy,
  type PolicyOperation,
  serializePolicy,
} from './utils/policy.js';

export class PolicyGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const modelsWithPolicies = this.schema.models.filter(hasPolicies);

    const policyEntries = modelsWithPolicies.map((model) => {
      const policies = normalizePolicies(model);
      const serializedPolicies = policies.map((policy) => serializePolicy(policy)).join(',\n    ');
      return `  ${model.name}: [\n    ${serializedPolicies},\n  ]`;
    });

    return [
      '// Auto-generated by PolicyGenerator. Do not edit manually.',
      `import type { NormalizedPolicy } from '${PACKAGE_NAME}/api/auth/policy';`,
      '',
      'export const POLICIES: Record<string, NormalizedPolicy[]> = {',
      policyEntries.join(',\n'),
      '};',
      '',
    ].join('\n');
  }
}

export function generatePoliciesFile(schema: Schema): string {
  return new PolicyGenerator(schema).generate();
}

export type { NormalizedPolicy, PolicyOperation };
