import type { Model, Schema } from '../schema-dsl/ast.js';
import { getPrimaryKey } from '../sql-generator/utils/ast-helpers.js';
import { getClientExportName } from '../db/type-generator.js';
import { toRouteBasePath, toRouteFileName } from '../api/utils/route-naming.js';

export class RouteGenerator {
  constructor(
    private readonly model: Model,
    private readonly schema: Schema,
  ) {}

  generate(): string {
    const clientKey = getClientExportName(this.model.name);
    const primaryKey = getPrimaryKey(this.model);
    if (!primaryKey) {
      throw new Error(`Model ${this.model.name} has no primary key`);
    }

    const pathParams = primaryKey.fields.map((field) => `:${field}`).join('/');
    const whereFromParams = primaryKey.fields.map((field) => `${field}: params.${field}`).join(', ');
    const paramSchemaName = `${this.model.name}ParamSchema`;

    return [
      '// Auto-generated by RouteGenerator. Do not edit manually.',
      "import { Hono } from 'hono';",
      "import type { AppEnv } from '../../src/api/types.js';",
      "import { validateJson, validateParam } from '../../src/api/middleware/validate.js';",
      "import { notFoundResponse } from '../../src/api/middleware/errors.js';",
      `import {`,
      `  ${this.model.name}CreateSchema,`,
      `  ${this.model.name}UpdateSchema,`,
      `  ${paramSchemaName},`,
      `} from '../schemas/validation.js';`,
      '',
      'const router = new Hono<AppEnv>();',
      '',
      "router.get('/', async (c) => {",
      '  const db = c.get(\'db\');',
      `  const rows = await db.${clientKey}.findMany();`,
      '  return c.json(rows);',
      '});',
      '',
      `router.get('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const params = c.req.valid(\'param\');',
      `  const row = await db.${clientKey}.findUnique({ ${whereFromParams} });`,
      '  if (!row) {',
      '    return notFoundResponse(c);',
      '  }',
      '  return c.json(row);',
      '});',
      '',
      `router.post('/', validateJson(${this.model.name}CreateSchema), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const body = c.req.valid(\'json\');',
      `  const row = await db.${clientKey}.create(body);`,
      '  return c.json(row, 201);',
      '});',
      '',
      `router.put('/${pathParams}', validateParam(${paramSchemaName}), validateJson(${this.model.name}UpdateSchema), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const params = c.req.valid(\'param\');',
      '  const body = c.req.valid(\'json\');',
      `  const row = await db.${clientKey}.update({ where: { ${whereFromParams} }, data: body });`,
      '  return c.json(row);',
      '});',
      '',
      `router.delete('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const params = c.req.valid(\'param\');',
      `  const row = await db.${clientKey}.delete({ ${whereFromParams} });`,
      '  return c.json(row);',
      '});',
      '',
      'export default router;',
      '',
    ].join('\n');
  }

  getRouteFileName(): string {
    return toRouteFileName(this.model.name);
  }

  getRouteBasePath(): string {
    return toRouteBasePath(this.model.name);
  }
}

export function generateRouteFiles(schema: Schema): Map<string, string> {
  const files = new Map<string, string>();

  for (const model of schema.models) {
    const generator = new RouteGenerator(model, schema);
    files.set(generator.getRouteFileName(), generator.generate());
  }

  return files;
}

export function getRouteMountEntries(schema: Schema): { basePath: string; fileName: string; importName: string }[] {
  return schema.models.map((model) => {
    const basePath = toRouteBasePath(model.name);
    const fileName = toRouteFileName(model.name);
    const importName = toRouteImportName(basePath);
    return { basePath, fileName, importName };
  });
}

function toRouteImportName(basePath: string): string {
  return basePath.replace(/-([a-z])/g, (_, char: string) => char.toUpperCase()) + 'Router';
}
