import { PACKAGE_NAME } from '../constants.js';
import type { Model, Schema } from '../schema-dsl/ast.js';
import { getPrimaryKey } from '../sql-generator/utils/ast-helpers.js';
import { getClientExportName } from '../db/type-generator.js';
import { toRouteBasePath, toRouteFileName, toRouteImportName } from '../api/utils/route-naming.js';
import { toModelConstantPrefix } from './utils/api-fields.js';
import { hasPolicies } from './utils/policy.js';

export class RouteGenerator {
  constructor(
    private readonly model: Model,
    private readonly schema: Schema,
  ) {}

  generate(): string {
    const clientKey = getClientExportName(this.model.name);
    const primaryKey = getPrimaryKey(this.model);
    if (!primaryKey) {
      throw new Error(`Model ${this.model.name} has no primary key`);
    }

    const pathParams = primaryKey.fields.map((field) => `:${field}`).join('/');
    const whereFromParams = primaryKey.fields.map((field) => `${field}: params.${field}`).join(', ');
    const paramSchemaName = `${this.model.name}ParamSchema`;
    const listQuerySchemaName = `${this.model.name}ListQuerySchema`;
    const modelHasPolicies = hasPolicies(this.model);
    const constantPrefix = toModelConstantPrefix(this.model.name);

    return [
      '// Auto-generated by RouteGenerator. Do not edit manually.',
      "import { Hono } from 'hono';",
      `import type { AppEnv } from '${PACKAGE_NAME}/api/types';`,
      `import { validateJson, validateParam, validateQuery } from '${PACKAGE_NAME}/api/middleware/validate';`,
      `import { notFoundResponse } from '${PACKAGE_NAME}/api/middleware/errors';`,
      `import { buildListQuery } from '${PACKAGE_NAME}/api/utils/list-query';`,
      `import { omitFields, omitFieldsMany } from '${PACKAGE_NAME}/api/utils/omit-fields';`,
      ...(modelHasPolicies
        ? [
            `import { assertPolicy, mergeWhere, resolvePolicyWhere } from '${PACKAGE_NAME}/api/auth/policy';`,
          ]
        : []),
      `import {`,
      `  ${this.model.name}CreateSchema,`,
      `  ${this.model.name}UpdateSchema,`,
      `  ${paramSchemaName},`,
      `  ${listQuerySchemaName},`,
      `  ${constantPrefix}_LIST_QUERY_FIELDS,`,
      `  ${constantPrefix}_OMIT_FIELDS,`,
      `  ${constantPrefix}_SORTABLE_FIELDS,`,
      `} from '../schemas/validation.js';`,
      '',
      'const router = new Hono<AppEnv>();',
      '',
      ...this.generateListRoute(clientKey, modelHasPolicies, listQuerySchemaName, constantPrefix),
      '',
      ...this.generateGetRoute(
        clientKey,
        pathParams,
        paramSchemaName,
        whereFromParams,
        modelHasPolicies,
        constantPrefix,
      ),
      '',
      ...this.generateCreateRoute(clientKey, modelHasPolicies, constantPrefix),
      '',
      ...this.generateUpdateRoute(
        clientKey,
        pathParams,
        paramSchemaName,
        whereFromParams,
        modelHasPolicies,
        constantPrefix,
      ),
      '',
      ...this.generateDeleteRoute(
        clientKey,
        pathParams,
        paramSchemaName,
        whereFromParams,
        modelHasPolicies,
        constantPrefix,
      ),
      '',
      'export default router;',
      '',
    ].join('\n');
  }

  private jsonRow(variableName: string, constantPrefix: string, statusCode?: number): string {
    const payload = `omitFields(${variableName}, ${constantPrefix}_OMIT_FIELDS)`;
    if (statusCode === undefined) {
      return `c.json(${payload})`;
    }

    return `c.json(${payload}, ${statusCode})`;
  }

  private jsonRows(variableName: string, constantPrefix: string): string {
    return `c.json(omitFieldsMany(${variableName}, ${constantPrefix}_OMIT_FIELDS))`;
  }

  private generateListRoute(
    clientKey: string,
    modelHasPolicies: boolean,
    listQuerySchemaName: string,
    constantPrefix: string,
  ): string[] {
    const listQueryBlock = [
      `  const query = c.req.valid('query');`,
      `  const { where, orderBy, take, skip } = buildListQuery(`,
      `    query,`,
      `    ${constantPrefix}_LIST_QUERY_FIELDS,`,
      `    ${constantPrefix}_SORTABLE_FIELDS,`,
      `  );`,
    ];

    if (!modelHasPolicies) {
      return [
        `router.get('/', validateQuery(${listQuerySchemaName}), async (c) => {`,
        '  const db = c.get(\'db\');',
        ...listQueryBlock,
        `  const rows = await db.${clientKey}.findMany({ where, orderBy, take, skip });`,
        `  return ${this.jsonRows('rows', constantPrefix)};`,
        '});',
      ];
    }

    return [
      `router.get('/', validateQuery(${listQuerySchemaName}), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const auth = c.get(\'auth\');',
      `  const policy = assertPolicy('${this.model.name}', auth.role, 'select');`,
      '  const policyWhere = resolvePolicyWhere(policy, auth);',
      ...listQueryBlock,
      `  const rows = await db.${clientKey}.findMany({`,
      '    where: mergeWhere(where, policyWhere),',
      '    orderBy,',
      '    take,',
      '    skip,',
      '  });',
      `  return ${this.jsonRows('rows', constantPrefix)};`,
      '});',
    ];
  }

  private generateGetRoute(
    clientKey: string,
    pathParams: string,
    paramSchemaName: string,
    whereFromParams: string,
    modelHasPolicies: boolean,
    constantPrefix: string,
  ): string[] {
    if (!modelHasPolicies) {
      return [
        `router.get('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
        '  const db = c.get(\'db\');',
        '  const params = c.req.valid(\'param\');',
        `  const row = await db.${clientKey}.findUnique({ ${whereFromParams} });`,
        '  if (!row) {',
        '    return notFoundResponse(c);',
        '  }',
        `  return ${this.jsonRow('row', constantPrefix)};`,
        '});',
      ];
    }

    return [
      `router.get('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const auth = c.get(\'auth\');',
      `  const policy = assertPolicy('${this.model.name}', auth.role, 'select');`,
      '  const policyWhere = resolvePolicyWhere(policy, auth);',
      '  const params = c.req.valid(\'param\');',
      `  const row = await db.${clientKey}.findUnique(mergeWhere({ ${whereFromParams} }, policyWhere));`,
      '  if (!row) {',
      '    return notFoundResponse(c);',
      '  }',
      `  return ${this.jsonRow('row', constantPrefix)};`,
      '});',
    ];
  }

  private generateCreateRoute(
    clientKey: string,
    modelHasPolicies: boolean,
    constantPrefix: string,
  ): string[] {
    if (!modelHasPolicies) {
      return [
        `router.post('/', validateJson(${this.model.name}CreateSchema), async (c) => {`,
        '  const db = c.get(\'db\');',
        '  const body = c.req.valid(\'json\');',
        `  const row = await db.${clientKey}.create(body);`,
        `  return ${this.jsonRow('row', constantPrefix, 201)};`,
        '});',
      ];
    }

    return [
      `router.post('/', validateJson(${this.model.name}CreateSchema), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const auth = c.get(\'auth\');',
      `  assertPolicy('${this.model.name}', auth.role, 'insert');`,
      '  const body = c.req.valid(\'json\');',
      `  const row = await db.${clientKey}.create(body);`,
      `  return ${this.jsonRow('row', constantPrefix, 201)};`,
      '});',
    ];
  }

  private generateUpdateRoute(
    clientKey: string,
    pathParams: string,
    paramSchemaName: string,
    whereFromParams: string,
    modelHasPolicies: boolean,
    constantPrefix: string,
  ): string[] {
    if (!modelHasPolicies) {
      return [
        `router.put('/${pathParams}', validateParam(${paramSchemaName}), validateJson(${this.model.name}UpdateSchema), async (c) => {`,
        '  const db = c.get(\'db\');',
        '  const params = c.req.valid(\'param\');',
        '  const body = c.req.valid(\'json\');',
        `  const row = await db.${clientKey}.update({ where: { ${whereFromParams} }, data: body });`,
        `  return ${this.jsonRow('row', constantPrefix)};`,
        '});',
      ];
    }

    return [
      `router.put('/${pathParams}', validateParam(${paramSchemaName}), validateJson(${this.model.name}UpdateSchema), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const auth = c.get(\'auth\');',
      `  const policy = assertPolicy('${this.model.name}', auth.role, 'update');`,
      '  const policyWhere = resolvePolicyWhere(policy, auth);',
      '  const params = c.req.valid(\'param\');',
      '  const body = c.req.valid(\'json\');',
      `  const row = await db.${clientKey}.update({ where: mergeWhere({ ${whereFromParams} }, policyWhere), data: body });`,
      `  return ${this.jsonRow('row', constantPrefix)};`,
      '});',
    ];
  }

  private generateDeleteRoute(
    clientKey: string,
    pathParams: string,
    paramSchemaName: string,
    whereFromParams: string,
    modelHasPolicies: boolean,
    constantPrefix: string,
  ): string[] {
    if (!modelHasPolicies) {
      return [
        `router.delete('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
        '  const db = c.get(\'db\');',
        '  const params = c.req.valid(\'param\');',
        `  const row = await db.${clientKey}.delete({ ${whereFromParams} });`,
        `  return ${this.jsonRow('row', constantPrefix)};`,
        '});',
      ];
    }

    return [
      `router.delete('/${pathParams}', validateParam(${paramSchemaName}), async (c) => {`,
      '  const db = c.get(\'db\');',
      '  const auth = c.get(\'auth\');',
      `  const policy = assertPolicy('${this.model.name}', auth.role, 'delete');`,
      '  const policyWhere = resolvePolicyWhere(policy, auth);',
      '  const params = c.req.valid(\'param\');',
      `  const row = await db.${clientKey}.delete(mergeWhere({ ${whereFromParams} }, policyWhere));`,
      `  return ${this.jsonRow('row', constantPrefix)};`,
      '});',
    ];
  }

  getRouteFileName(): string {
    return toRouteFileName(this.model.name);
  }

  getRouteBasePath(): string {
    return toRouteBasePath(this.model.name);
  }
}

export function generateRouteFiles(schema: Schema): Map<string, string> {
  const files = new Map<string, string>();

  for (const model of schema.models) {
    const generator = new RouteGenerator(model, schema);
    files.set(generator.getRouteFileName(), generator.generate());
  }

  return files;
}

export function getRouteMountEntries(schema: Schema): { basePath: string; fileName: string; importName: string }[] {
  return schema.models.map((model) => {
    const basePath = toRouteBasePath(model.name);
    const fileName = toRouteFileName(model.name);
    const importName = toRouteImportName(basePath);
    return { basePath, fileName, importName };
  });
}
