import { PACKAGE_NAME } from '../constants.js';
import type { Field, Model, Schema } from '../schema-dsl/ast.js';
import {
  fieldHasAttribute,
  getFieldAttribute,
  getModelNames,
  getOptionalKvPair,
  getPrimaryKey,
  getStoredFields,
} from '../sql-generator/utils/ast-helpers.js';
import {
  buildIncludableRelationTree,
  buildRelationTargets,
  getFilterableFields,
  getOmittedFields,
  getSortableFieldNames,
  toModelConstantPrefix,
} from './utils/api-fields.js';
import {
  buildFilterFieldMeta,
  queryParamKey,
  toFilterZodType,
  type FilterOperator,
} from './utils/filter-operators.js';

export class ZodSchemaGenerator {
  constructor(private readonly schema: Schema) {}

  generate(): string {
    const typeImports = this.schema.models.map((model) => model.name).join(',\n  ');
    const modelBlocks = this.schema.models.flatMap((model) => this.generateModelSchemas(model));

    return [
      '// Auto-generated by ZodSchemaGenerator. Do not edit manually.',
      "import { z } from 'zod';",
      `import { validateIncludePaths } from '${PACKAGE_NAME}/api/utils/include-query';`,
      `import type {\n  ${typeImports},\n} from '../db-types.js';`,
      '',
      ...modelBlocks,
      this.generateGlobalMetadata(),
    ].join('\n');
  }

  private generateGlobalMetadata(): string {
    const omitByModel = Object.fromEntries(
      this.schema.models.map((model) => [
        model.name,
        getOmittedFields(model, this.schema).map((field) => field.name),
      ]),
    );
    const relationTargets = Object.fromEntries(
      this.schema.models.map((model) => [
        model.name,
        buildRelationTargets(model, this.schema),
      ]),
    );

    return [
      `export const API_OMIT_FIELDS_BY_MODEL = ${JSON.stringify(omitByModel, null, 2)} as const;`,
      `export const API_RELATION_TARGETS = ${JSON.stringify(relationTargets, null, 2)} as const;`,
      '',
    ].join('\n');
  }

  private generateModelSchemas(model: Model): string[] {
    const modelNames = getModelNames(this.schema);
    const storedFields = getStoredFields(model, modelNames);
    const primaryKey = getPrimaryKey(model);
    const pkFields = new Set(primaryKey?.fields ?? []);

    const createFields = storedFields.filter((field) => !pkFields.has(field.name));
    const updateFields = storedFields.filter((field) => !pkFields.has(field.name));
    const pkFieldDefs = storedFields.filter((field) => pkFields.has(field.name));

    const createLines = createFields.map((field) => this.generateObjectField(field, 'create'));
    const updateLines = updateFields.map((field) => this.generateObjectField(field, 'update'));
    const paramLines = pkFieldDefs.map((field) => this.generateParamField(field));

    const blocks: string[] = [
      `export const ${model.name}CreateSchema = z.object({`,
      ...createLines.map((line) => `  ${line},`),
      `});\n`,
      `export const ${model.name}UpdateSchema = z.object({`,
      ...updateLines.map((line) => `  ${line},`),
      `});\n`,
    ];

    if (paramLines.length > 0) {
      blocks.push(
        `export const ${model.name}ParamSchema = z.object({`,
        ...paramLines.map((line) => `  ${line},`),
        `});\n`,
      );
    }

    blocks.push(...this.generateListQuerySchemas(model));

    return blocks;
  }

  private generateListQuerySchemas(model: Model): string[] {
    const prefix = toModelConstantPrefix(model.name);
    const filterableFields = getFilterableFields(model, this.schema);
    const sortableFields = getSortableFieldNames(model, this.schema);
    const omittedFields = getOmittedFields(model, this.schema);
    const filterFieldMeta = filterableFields.map((field) => buildFilterFieldMeta(field, this.schema));

    const queryLines = filterableFields.flatMap((field) =>
      this.generateListQueryFieldLines(field, filterFieldMeta.find((meta) => meta.name === field.name)!),
    );

    queryLines.push(
      'limit: z.coerce.number().int().min(1).max(100).optional(),',
      'offset: z.coerce.number().int().min(0).optional(),',
      'sort: z.string().optional(),',
      'include: z.string().optional(),',
    );

    const sortableLiteral = sortableFields.map((field) => `'${field}'`).join(', ');
    const listQueryFieldsJson = JSON.stringify(filterFieldMeta, null, 2);
    const omitFieldNames = omittedFields.map((field) => field.name);
    const omitFieldsJson = JSON.stringify(omitFieldNames);
    const includableRelationsJson = JSON.stringify(
      buildIncludableRelationTree(model, this.schema),
      null,
      2,
    );

    const responseType =
      omittedFields.length === 0
        ? `export type ${model.name}Response = ${model.name};`
        : `export type ${model.name}Response = Omit<${model.name}, ${omitFieldNames.map((name) => `'${name}'`).join(' | ')}>;`;

    return [
      `export const ${prefix}_SORTABLE_FIELDS = [${sortableLiteral}] as const;`,
      `export const ${prefix}_LIST_QUERY_FIELDS = ${listQueryFieldsJson} as const;`,
      `export const ${prefix}_INCLUDABLE_RELATIONS = ${includableRelationsJson} as const;`,
      `export const ${prefix}_OMIT_FIELDS = ${omitFieldsJson} as const;`,
      responseType + '\n',
      `export const ${model.name}GetQuerySchema = z`,
      '  .object({',
      '    include: z.string().optional(),',
      '  })',
      ...this.generateIncludeRefinement(prefix),
      '\n',
      `export const ${model.name}ListQuerySchema = z`,
      '  .object({',
      ...queryLines.map((line) => `    ${line}`),
      '  })',
      ...this.generateReadQueryRefinement(prefix),
      '\n',
    ];
  }

  private generateIncludeRefinement(prefix: string): string[] {
    return [
      '  .superRefine((data, ctx) => {',
      '    if (data.include === undefined) {',
      '      return;',
      '    }',
      `    const includeError = validateIncludePaths(data.include, ${prefix}_INCLUDABLE_RELATIONS);`,
      '    if (includeError) {',
      '      ctx.addIssue({',
      '        code: \'custom\',',
      '        message: includeError,',
      '        path: [\'include\'],',
      '      });',
      '    }',
      '  });\n',
    ];
  }

  private generateReadQueryRefinement(prefix: string): string[] {
    return [
      '  .superRefine((data, ctx) => {',
      '    if (data.sort !== undefined) {',
      '      const descending = data.sort.startsWith(\'-\');',
      '      const field = descending ? data.sort.slice(1) : data.sort;',
      `      if (!(${prefix}_SORTABLE_FIELDS as readonly string[]).includes(field)) {`,
      '        ctx.addIssue({',
      '          code: \'custom\',',
      '          message: `Invalid sort field "${field}"`,',
      '          path: [\'sort\'],',
      '        });',
      '      }',
      '    }',
      '    if (data.include !== undefined) {',
      `      const includeError = validateIncludePaths(data.include, ${prefix}_INCLUDABLE_RELATIONS);`,
      '      if (includeError) {',
      '        ctx.addIssue({',
      '          code: \'custom\',',
      '          message: includeError,',
      '          path: [\'include\'],',
      '        });',
      '      }',
      '    }',
      '  });\n',
    ];
  }

  private generateListQueryFieldLines(field: Field, meta: ReturnType<typeof buildFilterFieldMeta>): string[] {
    const lines: string[] = [];

    for (const operator of meta.operators) {
      const key = queryParamKey(field.name, operator as FilterOperator);
      const zodType = toFilterZodType(field.type, field, this.schema, operator as FilterOperator, true);
      lines.push(`${key}: ${zodType}.optional(),`);
    }

    return lines;
  }

  private generateObjectField(field: Field, mode: 'create' | 'update'): string {
    const zodType = this.toZodType(field, mode);
    const fieldName = `${field.name}: ${zodType}`;

    if (mode === 'update') {
      return fieldName;
    }

    const isOptional = field.type.optional || fieldHasAttribute(field, 'default');
    if (isOptional) {
      return `${field.name}: ${zodType}.optional()`;
    }

    return fieldName;
  }

  private generateParamField(field: Field): string {
    const zodType = this.toParamZodType(field);
    return `${field.name}: ${zodType}`;
  }

  private toParamZodType(field: Field): string {
    switch (field.type.name) {
      case 'UUID':
        return 'z.string().uuid()';
      case 'INTEGER':
      case 'SERIAL':
      case 'SMALLINT':
        return 'z.coerce.number().int()';
      default:
        return 'z.string()';
    }
  }

  private toZodType(field: Field, mode: 'create' | 'update'): string {
    let zodType = this.mapBaseZodType(field.type, field);

    zodType = this.applyValidationRules(field, zodType);

    if (field.type.optional) {
      zodType = `${zodType}.nullable()`;
    }

    if (mode === 'update') {
      zodType = `${zodType}.optional()`;
    }

    return zodType;
  }

  private mapBaseZodType(type: Field['type'], field: Field): string {
    const enumType = this.schema.enums.find((enumDef) => enumDef.name === type.name);
    if (enumType) {
      const values = enumType.values.map((value) => `'${value}'`).join(', ');
      return `z.enum([${values}])`;
    }

    if (type.array && type.name === 'TEXT') {
      return 'z.array(z.string())';
    }

    switch (type.name) {
      case 'UUID':
      case 'VARCHAR':
      case 'TEXT':
        return 'z.string()';
      case 'INTEGER':
      case 'SERIAL':
      case 'SMALLINT':
        return 'z.number().int()';
      case 'BOOLEAN':
        return 'z.boolean()';
      case 'TIMESTAMP':
        return 'z.coerce.date()';
      case 'DECIMAL':
        return 'z.string()';
      case 'JSONB':
        return 'z.record(z.unknown())';
      case 'POINT':
        return 'z.unknown()';
      default:
        return 'z.unknown()';
    }
  }

  private applyValidationRules(field: Field, zodType: string): string {
    const regexAttr = getFieldAttribute(field, 'regex');
    if (regexAttr?.args?.kind === 'KeyValueArgs') {
      const pattern = getOptionalKvPair(regexAttr.args, 'pattern');
      const message = getOptionalKvPair(regexAttr.args, 'message');
      if (pattern?.value.kind === 'StringLiteral' && message?.value.kind === 'StringLiteral') {
        const escapedPattern = this.escapeRegexLiteral(pattern.value.value);
        const escapedMessage = this.escapeStringLiteral(message.value.value);
        zodType = `${zodType}.regex(/${escapedPattern}/, { message: '${escapedMessage}' })`;
      }
    }

    const rangeAttr = getFieldAttribute(field, 'range');
    if (rangeAttr?.args?.kind === 'KeyValueArgs') {
      const min = getOptionalKvPair(rangeAttr.args, 'min');
      const max = getOptionalKvPair(rangeAttr.args, 'max');
      const message = getOptionalKvPair(rangeAttr.args, 'message');
      if (
        min?.value.kind === 'NumberLiteral' &&
        max?.value.kind === 'NumberLiteral' &&
        message?.value.kind === 'StringLiteral'
      ) {
        const escapedMessage = this.escapeStringLiteral(message.value.value);
        zodType = `${zodType}.min(${min.value.value}, { message: '${escapedMessage}' }).max(${max.value.value}, { message: '${escapedMessage}' })`;
      }
    }

    return zodType;
  }

  private escapeRegexLiteral(pattern: string): string {
    return pattern.replace(/\//g, '\\/');
  }

  private escapeStringLiteral(value: string): string {
    return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
  }
}

export function generateValidationSchemas(schema: Schema): string {
  return new ZodSchemaGenerator(schema).generate();
}
